### PR TITLE
chore: blacken the code base

### PR DESCRIPTION
**Pull request by nilleb**
Commodity pull request allowing @aconrad to inspect changes made by `black`

### CODE REVIEW

**Comment by aconrad** [comment]
Do we still need this PR?

**Comment by nilleb** [comment]
It's up to you to decide whether you want to blacken automatically pycobertura code.

**Comment by aconrad** [comment]
Didn't we already merge something for doing that?

**Comment by nilleb** [comment]
Yeah, you're right. Closing. 🙏🏻

**Pull request closed without merging**
